### ISSUE TITLE
Payment model name is not provided in config

### ISSUE THREAD

**Issue by SanderAtom** [cardgate/magento2#9]
I've installed Cardgate/magento2 (Cardgate_Payment) module v2.0.9 on my Magento 2.2.0 project (also tried 2.2.2). I've setup a test account but when I open the checkout page it's throwing the following error:

```
1 exception(s):
Exception #0 (UnexpectedValueException): Payment model name is not provided in config!

Exception #0 (UnexpectedValueException): Payment model name is not provided in config!
#0 [dir]/vendor/magento/module-payment/Model/PaymentMethodList.php(46): Magento\Payment\Helper\Data->getMethodInstance('cardgate_ideal')
#1 [internal function]: Magento\Payment\Model\PaymentMethodList->Magento\Payment\Model\{closure}('cardgate_ideal')
#2 [dir]/vendor/magento/module-payment/Model/PaymentMethodList.php(48): array_map(Object(Closure), Array)
#3 [dir]/vendor/magento/module-payment/Model/PaymentMethodList.php(84): Magento\Payment\Model\PaymentMethodList->getList('1')
#4 [dir]/vendor/magento/module-vault/Plugin/PaymentVaultConfigurationProcess.php(63): Magento\Payment\Model\PaymentMethodList->getActiveList('1')
#5 [dir]/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Vault\Plugin\PaymentVaultConfigurationProcess->beforeProcess(Object(Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor), Array)
#6 [dir]/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->Magento\Framework\Interception\{closure}(Array)
#7 [dir]/generated/code/Magento/Checkout/Block/Checkout/LayoutProcessor/Interceptor.php(26): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->___callPlugins('process', Array, Array)
#8 [dir]/vendor/magento/module-checkout/Block/Onepage.php(78): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->process(Array)
#9 [dir]/vendor/magento/module-checkout/view/frontend/templates/onepage.phtml(21): Magento\Checkout\Block\Onepage->getJsLayout()
#10 [dir]/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('[dir]/D...')
#11 [dir]/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage), '[dir]/D...', Array)
#12 [dir]/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('[dir]/D...')
#13 [dir]/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#14 [dir]/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 [dir]/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('checkout.root')
#16 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.root')
#17 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.root')
#18 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.root', true)
#19 [dir]/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.root')
#20 [dir]/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#21 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#22 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#23 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#24 [dir]/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#25 [dir]/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main')
#26 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#27 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#28 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#29 [dir]/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#30 [dir]/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns')
#31 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#32 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#33 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#34 [dir]/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#35 [dir]/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content')
#36 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#37 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#38 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#39 [dir]/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#40 [dir]/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#41 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#42 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#43 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#44 [dir]/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#45 [dir]/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#46 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#47 [dir]/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#48 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#49 [dir]/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#50 [dir]/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#51 [dir]/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#52 [dir]/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#53 [dir]/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#54 [dir]/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#55 [dir]/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#56 [dir]/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 [dir]/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#58 [dir]/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 [dir]/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#60 [dir]/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 [dir]/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#62 [dir]/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#63 [dir]/.composer/vendor/weprovide/valet-plus/server.php(117): require('[dir]/D...')
#64 {main}
```

**Comment by cardgate** [comment]
Thank you for reporting this issue. None of our test environments appear to be affected by this bug, which makes it a lot harder to fix. Is it possible for you to test release v2.0.10 and see if the problem still exists?

**Comment by cardgate** [comment]
Also, make sure to clear the cache and run the following commands:
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean

**Comment by SanderAtom** [comment]
I've just done these steps:
- installed a clean Magento v2.2.2 composer project
- `bin/magento deploy:mode:set developer`
- `composer require cardgate/magento2` it installed v2.0.10
- `bin/magento module:enable Cardgate_Payment`
- `bin/magento setup:upgrade`
- `bin/magento setup:di:compile`
- `bin/magento cache:clean`
- add a product in de admin
- add product to cart
- go to /checkout/
Then the error `Payment model name is not provided in config!` pops up.

**Comment by cardgate** [comment]
Does your version include the patch you've issued? Can you try without the patch and with the default template (since you've mentioned that without the patch your template doesn't work)?

**Comment by SanderAtom** [comment]
True I had the patch installed. Without it, it does seem to work in a clean 2.2.2 install. So I'm back with the problem that the template is missing after I install the cardgate module.

**Comment by cardgate** [comment]
I've made some changes to your patch which I would like you to try. Can you try the current development version to see if it solves the problems with your theme?

```
composer require cardgate/magento2 dev-master
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:clean
```

**Comment by SanderAtom** [comment]
The dev version seems to work yes, no template errors and I have payment methods in the checkout.

**Comment by cardgate** [comment]
Thank you for your effort, I'll prep a new release asap.
